name: birdle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^9.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "yes"
  ios: "yes"
  image_path: "assets/logo_original.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo_original.png
    - assets/logo_appbar.png
